spring:
  application:
    name: ${APP_NAME:orchestrator}

server:
  port: ${SERVER_PORT:7018}

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER_URL:http://localhost:8761/eureka/}

management:
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: ${ZIPKIN_URL:http://localhost:9411/api/v2/spans}

api:
  base-path: ${API_BASE_PATH:/api/v1}

services:
  bucket:
    clear-url: ${BUCKET_CLEAR_URL:/api/v1/clear}
    restore-url: ${BUCKET_RESTORE_URL:/api/v1/restore}
  client:
    deduct-url: ${CLIENT_DEDUCT_URL:/api/v1/deduct}
    restore-url: ${CLIENT_RESTORE_URL:/api/v1/restore}
  order:
    create-url: ${ORDER_CREATE_URL:/api/v1/create}
    remove-url: ${ORDER_REMOVE_URL:/api/v1/remove}


resilience:
  retry:
    max-attempts: ${RETRY_MAX_ATTEMPTS:3}
    wait-duration: ${RETRY_WAIT_DURATION:1s}
    suffix: ${RETRY_SUFFIX:RevertRetry}

logging:
  pattern:
    console: "%clr(%d{HH:mm:ss.SSS}){faint} %clr(${LOG_LEVEL_PATTERN:-%5p}) %clr(---){faint} %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n${LOG_EXCEPTION_CONVERSION_WORD:-%wEx}"
    level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"
  level:
    root: info
    org.springframework: warn
    com.zaxxer.hikari: warn
    org.hibernate: warn
    com.netflix.discovery: warn
    com.serjnn: info
